resources:
- bases/role.yaml
- bases/role_binding.yaml
# Comment the following 4 lines if you want to disable
# the auth proxy (https://github.com/brancz/kube-rbac-proxy)
# which protects your /metrics endpoint.
- bases/api_manager_role.yaml
- bases/api_manager_role_binding.yaml
- bases/portal_manager_role.yaml
- bases/portal_manager_role_binding.yaml
- bases/auth_proxy_role.yaml
- bases/auth_proxy_role_binding.yaml
- bases/auth_proxy_client_clusterrole.yaml
- bases/scheduler_extender_role.yaml
- bases/scheduler_extender_role_binding.yaml
- bases/serviceaccount.yaml

patches:
  - path: role_patch.yaml
    target:
      kind: ClusterRole
      name: storageos-operator

# storageos-storageos:metrics-reader                                     2021-09-20T15:25:56Z
# storageos-storageos:operator                                           2021-09-20T15:25:56Z
# storageos-storageos:proxy                                              2021-09-20T15:25:56Z